# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Leo von Kleist
tagline: Blog
email: leonard.vkleist@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  CS Student @ ETH Zurich
baseurl: / # the subpath of your site, e.g. /blog
url: http://tsaprailis.com
github_username:  leokleist
linkedin_username: leonard von kleist

# Pagination
gems: [jekyll-paginate]
paginate:         5
paginate_path: "page:num"

# Permalinks
permalink: pretty
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true
  syntax_highlighter: rouge
excerpt_separator: "<!--excerpt-->"
