# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kostis Tsaprailis
tagline: Blog
email: kostis.tsaprailis@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Electrical & Computer Engineer, interested in more things than I can juggle.
baseurl: / # the subpath of your site, e.g. /blog
url: http://tsaprailis.com
twitter_username: ktsaprailis
github_username:  kostistsaprailis
linkedin_username: konstantinostsaprailis

# Pagination
gems: [jekyll-paginate]
paginate:         5
paginate_path: "page:num"

# Permalinks
permalink: pretty
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'
